In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [6]:
data=data = {
    "student_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115],
    "name": [
        "Mahesh", "Ravi", "Suresh", "Kiran", "Arjun",
        "Priya", "Divya", "Anjali", "Rahul", "Manoj",
        "Sneha", "Varun", "Pavan", "Keerthi", "Naveen"
    ],
    "gender": [
        "Male", "Male", "Male", "Male", "Male",
        "Female", "Female", "Female", "Male", "Male",
        "Female", "Male", "Male", "Female", "Male"
    ],
    "department": [
        "CSE", "ECE", "CSE", "EEE", "CSE",
        "IT", "CSE", "ECE", "IT", "EEE",
        "CSE", "IT", "ECE", "CSE", "EEE"
    ],
    "age": [21, 22, 21, 23, 22, 21, 22, 21, 23, 22, 21, 22, 23, 21, 22],
    "attendance": [95, 82, 68, 75, 91, 98, 88, 72, 65, 85, 96, 78, 89, 93, 70],
    "python": [92, 78, 65, 72, 88, 96, 85, 70, 60, 82, 94, 75, 86, 91, 68],
    "java": [88, 75, 70, 68, 90, 92, 89, 65, 58, 80, 95, 72, 84, 93, 66],
    "sql": [95, 82, 60, 75, 85, 98, 90, 72, 55, 78, 96, 80, 88, 94, 62],
    "mathematics": [85, 80, 72, 65, 92, 94, 87, 68, 62, 75, 90, 78, 83, 96, 70],
    "statistics": [90, 76, 68, 70, 87, 95, 92, 75, 57, 84, 93, 73, 85, 89, 65]
}

df=pd.DataFrame(data)
df

,student_id,name,gender,department,age,attendance,python,java,sql,mathematics,statistics
0,101,Mahesh,Male,CSE,21,95,92,88,95,85,90
1,102,Ravi,Male,ECE,22,82,78,75,82,80,76
2,103,Suresh,Male,CSE,21,68,65,70,60,72,68
3,104,Kiran,Male,EEE,23,75,72,68,75,65,70
4,105,Arjun,Male,CSE,22,91,88,90,85,92,87
5,106,Priya,Female,IT,21,98,96,92,98,94,95
6,107,Divya,Female,CSE,22,88,85,89,90,87,92
7,108,Anjali,Female,ECE,21,72,70,65,72,68,75
8,109,Rahul,Male,IT,23,65,60,58,55,62,57
9,110,Manoj,Male,EEE,22,85,82,80,78,75,84
10,111,Sneha,Female,CSE,21,96,94,95,96,90,93
11,112,Varun,Male,IT,22,78,75,72,80,78,73
12,113,Pavan,Male,ECE,23,89,86,84,88,83,85
13,114,Keerthi,Female,CSE,21,93,91,93,94,96,89
14,115,Naveen,Male,EEE,22,70,68,66,62,70,65

In [7]:
df.isna().sum()

student_id     0
name           0
gender         0
department     0
age            0
attendance     0
python         0
java           0
sql            0
mathematics    0
statistics     0
dtype: int64

In [8]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
dtype: bool

In [9]:
df.describe()

,student_id,age,attendance,python,java,sql,mathematics,statistics
count,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000
mean,108.000000,21.800000,83.000000,80.133333,79.000000,80.666667,79.800000,79.933333
std,4.472136,0.774597,11.006492,11.363266,12.017844,13.704361,10.903473,11.640242
min,101.000000,21.000000,65.000000,60.000000,58.000000,55.000000,62.000000,57.000000
25%,104.500000,21.000000,73.500000,71.000000,69.000000,73.500000,71.000000,71.500000
50%,108.000000,22.000000,85.000000,82.000000,80.000000,82.000000,80.000000,84.000000
75%,111.500000,22.000000,92.000000,89.500000,89.500000,92.000000,88.500000,89.500000
max,115.000000,23.000000,98.000000,96.000000,95.000000,98.000000,96.000000,95.000000

In [10]:
df.shape

(15, 11)

In [12]:
df.columns

Index(['student_id', 'name', 'gender', 'department', 'age', 'attendance',
       'python', 'java', 'sql', 'mathematics', 'statistics'],
      dtype='object')

In [13]:
df["department"].value_counts()

department
CSE    6
ECE    3
EEE    3
IT     3
Name: count, dtype: int64

In [17]:

df.iloc[0:5, 0:4]

   student_id    name gender department
0         101  Mahesh   Male        CSE
1         102    Ravi   Male        ECE
2         103  Suresh   Male        CSE
3         104   Kiran   Male        EEE
4         105   Arjun   Male        CSE

In [18]:
df.loc[0:4,["name","department","python"]]

     name department  python
0  Mahesh        CSE      92
1    Ravi        ECE      78
2  Suresh        CSE      65
3   Kiran        EEE      72
4   Arjun        CSE      88